services:
  - type: web
    name: portfolio-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
    rootDir: server
